### ISSUE TITLE
Ship can move past the right of the screen, becoming invisible

### ISSUE THREAD

**Issue by stbarrientos** [iSkore/pewpew.js#2]
You can go off screen to the right. The solution is to modify line 167 and 168 of bundle.js

Line 176:
`if( P.Transform.X > _.view.offsetWidth )` should be `if( P.Transform.X > _.view.width )`

Line 168:
`P.Transform.X = _.view.offsetWidth - P.WIDTH_OFFSET;` should be `P.Transform.X = _.view.width - P.WIDTH_OFFSET;`

The difference is using width instead of offsetWidth. I'm not sure why you were using offsetWidth, so this might break other calculations you've made.

**Comment by iSkore** [comment]
Fixed in Commit: [3e9217ac1d86339178578d6504dc74799caff5bb](https://github.com/iSkore/shooterjs/commit/3e9217ac1d86339178578d6504dc74799caff5bb)
